### ISSUE TITLE
Black screen at startup

### ISSUE THREAD

**Issue by gregspruce** [Thomasims/TeardownUMF#5] opened 2020-12-22 13:57 UTC
Had this issue both yesterday before, and today after the main branch of teardown was updated. I had used both the master branch and the 0.5.0 github branches both times. Today with the 0.5.2 update, I also used the most recent copy of the 0.5.0 GH branch.

After copying the folder into the teardown install directory and running the .bat file, when I start the game, I never even get to the white splashcreen. Alt+F4 wont kill it, I have to alt+tab out and task manager kill the game.

**Comment by Thomasims** [comment] 2020-12-22 16:49
Verify your game files in steam to clear out the old modloader and reinstall the latest version.
I have merged the 0.5.0 branch into master.

**Comment by gregspruce** [comment] 2020-12-22 18:57
I had been completely uninstalling and clearing out orphaned files and
reinstalling teardown from steam each time with the same issue.
I'll try the new merges later today.

**Comment by Ocean47** [comment] 2021-01-10 01:40
I have been trying to install this for my son and getting the same black screen?  Any chance you figured out what was happening?

**Comment by TeardownFan** [comment] 2021-01-16 23:41
I am getting the same
![ruhhh](https://user-images.githubusercontent.com/77467605/105504366-70b26c80-5ca6-11eb-8b7a-d9309651d675.jpg)

**Comment by Thomasims** [comment] 2021-01-17 00:18
I can't reproduce this, I've reinstalled UMF multiple times on both experimental and main without seeing this.

The only times I've gotten a black screen on startup is when the base game files were broken by an outdated mod.

I won't be able to help without someone providing reproducible steps to get this issue.

**Comment by gregspruce** [comment] 2021-01-17 00:22
This week, I just deleted the whole thing (game, mods, umf, everything) and
tried with new, latest versions and the game launches now.

**Comment by TeardownFan** [comment] 2021-01-17 00:38
Also how will I know my version is 0.4.6 or 0.5.0

**Comment by berwil-1** [comment] 2021-01-17 16:56
> Also how will I know my version is 0.4.6 or 0.5.0

You will find the version number in the bottom right corner, you need a version that is 0.5.0 or above (0.5.X).
![version](https://user-images.githubusercontent.com/13751243/104850095-50249400-58ed-11eb-981f-492ffa45f292.png)

**Comment by TeardownFan** [comment] 2021-01-17 17:53
Thank you, it says 0.5.2 but it still does not work?



EDIT : 2 days ago I saw all tutorials in "how to download mods",none of them told me how to fix this.

**Comment by TeardownFan** [comment] 2021-01-17 23:07
I am waiting..

**Comment by SimonPlayz** [comment] 2021-01-18 10:28
i started the game with the UMF and it got a black screen so i closed it and got an notification from my antivirus and it said that Teardown.exe a virus was after i installed the UMF it said Virus Detected Name of Virus: IDP:Generic trojan

can you explain that??

and now i cant remove it from my antivirus quarantaine

and i had the teardown version 0.5.3

**Comment by Thomasims** [comment] 2021-01-18 10:49
@SimonPlayz UMF does not modify teardown.exe in any way so you have a bigger problem, check the code yourself if you don't believe me.

@TeardownFan Go through the installation guide again and make sure you use the correct paths. If that still doesn't work seek help on the Teardown discord as you'll get quicker help there...

This issue has gone too far off track so I'm going to close it as the original problem is solved. If an *actual* Issue with UMF still persists please open a new issue.

**Closed as completed by Thomasims** 2021-01-18 10:49 UTC
